apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd-app1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/webapp-1
    repoURL: https://github.com/FreeBootcamp6/Aks_ArgoCd.git
    targetRevision: HEAD
